---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: static-client-alias
---
apiVersion: v1
kind: Service
metadata:
  name: static-client-alias
spec:
  selector:
    app: static-client-alias
  ports:
    - port: 4321
      targetPort: 4321
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: static-client-alias
  name: static-client-alias
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-client-alias
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        #consul.hashicorp.com/connect-service-upstreams: 'nginx:1234'
        #consul.hashicorp.com/connect-service-upstreams: 'static-server:1234,nginx:1235,nginx-pod:1236,nginx-local-host:1237,consul-https:1238,httpbin:1239,nginx-local-host-ext:1240,mysql-ext:1241,httpbin-ip:1242,httpbin-ip-name:1242'
        consul.hashicorp.com/connect-service-upstreams: 'static-server:1234,nginx:1235,nginx-pod:1236,nginx-local-host:1237,consul-https:1238,httpbin:1239,nginx-local-host-ext:1240,mysql-ext:1241,httpbin-ip:1242,httpbin-ip-name:1243,nginx-local-host-name:1244,nginx-local-host-alias:1245,nginx-pub-host-alias:1246,tetarwal-de:1247,learn:1248,tetarwal-de-mysql:1249'
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
      labels:
        app: static-client-alias
    spec:
      serviceAccountName: static-client-alias
      restartPolicy: Always
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "foo.local"
        - "bar.local"
      - ip: "10.1.2.3"
        hostnames:
        - "foo.remote"
        - "bar.remote"
      - ip: "172.31.58.253"
        hostnames:
        - "hostalias.com"
      - ip: "44.192.79.187"
        hostnames:
        - "pubhostalias.com"
      containers:
        - name: static-client-alias
          #image: tutum/curl:latest
          image: curlimages/curl 
          ports:
            - containerPort: 4321
          command: ["/bin/sleep", "3650d"]
          #command: ['/bin/sh', '-c', '--']
          #args: ['while true; do sleep 30; done;']

