apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  labels:
    app: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: 'false'
        #consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/service-meta-version: "1"
        consul.hashicorp.com/service-tags: v1
      labels:
        app: mysql-db
    spec:
      serviceAccountName: mysql-db
      containers:
      - name: mysql-db
        image: mysql:5.7
        ports:
        - name: mysql-port
          containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-secrets
                key: rootPassword
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: my-secrets
                key: username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef: 
                name: my-secrets
                key: password
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: my-secrets
                key: database

