---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
      labels:
        app: nginx-pod
    spec:
      serviceAccountName: nginx-pod
      containers:
      - name: nginx-pod
        image: nginx:1.14.2
        ports:
        - containerPort: 80
