---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-pod-hostalias
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-hostalias
  labels:
    app: nginx-pod-hostalias
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-pod-hostalias
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
      labels:
        app: nginx-pod-hostalias
    spec:
      serviceAccountName: nginx-pod-hostalias
      #restartPolicy: Never
      restartPolicy: Always
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "foo.local"
        - "bar.local"
      - ip: "10.1.2.3"
        hostnames:
        - "foo.remote"
        - "bar.remote"
      containers:
      - name: nginx-pod-hostalias
        image: nginx:1.14.2
        ports:
        - containerPort: 80
