apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment
  labels:
    app: application-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-db
  template:
    metadata:
      labels:
        app: application-db
    spec:
      serviceAccountName: k8s-demo
      containers:
      - name: k8s-demo
        image: wardviaene/k8s-demo
        command: ["node", "index-db.js"]
        ports:
        - name: nodejs-port
          containerPort: 3000
        env:
          - name: MYSQL_HOST
            #value: database-service
            value: 100.24.72.90
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-secrets
                key: rootPassword
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: my-secrets
                key: database