apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-v1
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
        version: v1
      annotations:
        'consul.hashicorp.com/connect-service-protocol': 'http'
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/service-tags': 'v1'
        'consul.hashicorp.com/service-meta-version': '1'
    spec:
      containers:
      - name: nodejs
        image: vchaudh3/node-demo
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-v2
  labels:
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
        version: v2
      annotations:
        'consul.hashicorp.com/connect-service-protocol': 'http'
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/service-tags': 'v2'
        'consul.hashicorp.com/service-meta-version': '2'
    spec:
      containers:
      - name: nodejs
        image: vchaudh3/node-demo-v2
        ports:
        - containerPort: 8080

