global:
  name: consul
  datacenter: dc1

  tls:
    enabled: true
    caCert:
      secretName: consul-ca-cert
      secretKey: tls.crt
    caKey:
      secretName: consul-ca-key
      secretKey: tls.key

  federation:
    enabled: true
    createFederationSecret: true

  acls:
    manageSystemACLs: true # note true
    createReplicationToken: true # note true
    bootstrapToken:
      secretName: consul-bootstrap-acl-token
      secretKey: token

  gossipEncryption:
    secretName: consul-gossip-encryption-key
    secretKey: key

connectInject:
  enabled: true

controller:
  enabled: true

meshGateway:
  enabled: true
  replicas: 1

server:
  extraVolumes:
    - type: secret
      name: vault-config
      load: true
      items:
        - key: config
          path: vault-config.json