version:
  major: 1
  minor: 6
  patch: 0
  prerelease: "release"
jenkins:
  master:
    plugins:
      - configuration-as-code
      - job-dsl
      - plain-credentials
      - github
      - blueocean
      - openstack-cloud
      - pipeline-githubnotify-step
      - timestamper
      - simple-theme-plugin
dev:
  dseImages:
    - datastax/dse-server:6.8.4
  ossImages:
    - k8ssandra/cass-management-api:3.11.10-v0.1.24
  ubiDseImages:
    - datastax/dse-server:6.8.4-ubi7
  ubiOssImages:
    - datastax/cassandra:3.11.6-ubi7
  sharedImages:
    - datastax/cass-config-builder:1.0.3
