apiVersion: v1
kind: ServiceAccount
metadata:
  name: world-app-sm-enabled-dc2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: world-app-sm-enabled-dc2
    #version: v1
  name: world-app-sm-enabled-dc2-v1
spec:
  progressDeadlineSeconds: 2147483647
  #replicas: 3
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: world-app-sm-enabled-dc2
      #version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        #consul.hashicorp.com/connect-service-protocol: http
        consul.hashicorp.com/service-meta-version: "1"
        consul.hashicorp.com/service-tags: v1
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
        consul.hashicorp.com/connect-service-upstreams: 'world-app-sm-enabled-2-dc2:9999'
      creationTimestamp: null
      labels:
        app: world-app-sm-enabled-dc2
        #version: v1
    spec:
      serviceAccountName: world-app-sm-enabled-dc2
      containers:
      - env:
        - name: TEXT
          value: world-app-sm-enabled-dc2-v1
        - name: NEXT
          value: localhost:9999
        image: vchaudh3/http-echo
        imagePullPolicy: Always
        #name: world-app-sm-enabled-dc2-v1
        name: world-app-sm-enabled-dc2
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: world-app-sm-enabled-dc2
  name: world-app-sm-enabled-dc2
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: world-app-sm-enabled-dc2
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
