{
 "title": "Overview_Dashboard_http_gRPC",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "downstream_app",
    "query": "label_values(envoy_cluster_upstream_rq_xx,local_cluster)"
   },
   {
    "name": "upstream_app",
    "label": "upstream_app",
    "query": "label_values(envoy_cluster_upstream_rq_xx{local_cluster=~\"$downstream_app\"}, envoy_cluster_name)"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests/s",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{consul_upstream_service=~\"$upstream_app\",local_cluster=\"$downstream_app\", envoy_response_code_class=~\"2|4\"}[5m]))\r\n"
    }
   ]
  },
  {
   "title": "Errors/s",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{consul_upstream_service=~\"$upstream_app\",local_cluster=\"$downstream_app\", envoy_response_code_class=~\"5\"}[5m]))\r\n\r\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "content": "<div style=\"display: flex; align-items: center\">\n  <img src=\"https://www.datocms-assets.com/2885/1507928925-consul.svg\" alt=\"Consul Icon\">&nbsp;&nbsp;&nbsp;<span style=\"font-size: 22px\">HTTP: L7 Service</span>\n</div>\n<div style=\"font-size: 18px; margin-left: 32px; color: rgba(255, 255, 255, 0.5);\">\n  HTTP requests from the downstream service to the upstream service via the sidecar proxies.\n</div>"
  },
  {
   "title": "HTTP Requests (count)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_xx{local_cluster=\"$downstream_app\",envoy_cluster_name=\"$upstream_app\"}[5m])) by (envoy_response_code_class)\r\n",
     "legendFormat": "{{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "HTTP Requests (time)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$upstream_app\"} > 0) by (quantile)\r\n",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "sum(rate(envoy_cluster_external_upstream_rq_time_sum{envoy_cluster_name=\"$upstream_app\"}[5m]))/sum(rate(envoy_cluster_external_upstream_rq_time_count{envoy_cluster_name=\"$upstream_app\"}[5m]))\r\n",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 22 },
   "content": "<div style=\"display: flex; align-items: center\">\n  <img src=\"https://www.datocms-assets.com/2885/1507928925-consul.svg\" alt=\"Consul Icon\">&nbsp;&nbsp;&nbsp;<span style=\"font-size: 22px\">gRPC: L7 Service</span>\n</div>\n<div style=\"font-size: 18px; margin-left: 32px; color: rgba(255, 255, 255, 0.5);\">\n  gRPC requests from the downstream service to the upstream service via the sidecar proxies.\n</div>"
  },
  {
   "title": "gRPC Methods (count)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_grpc_total[5m])) by (envoy_grpc_bridge_method)\r\n",
     "legendFormat": "{{envoy_grpc_bridge_method}}"
    }
   ]
  },
  {
   "title": "gRPC Requests (count)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{local_cluster=\"$downstream_app\",envoy_cluster_name=\"$upstream_app\"}[5m])) by (envoy_response_code_class)\r\n",
     "legendFormat": "{{envoy_response_code_class}}xx"
    }
   ]
  }
 ]
}