apiVersion: v1
kind: ServiceAccount
metadata:
  name: static-client
---
apiVersion: v1
kind: Service
metadata:
  name: static-client
spec:
  selector:
    app: static-client
  ports:
    - port: 4321
      targetPort: 4321
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: static-client
  name: static-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-client
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        #consul.hashicorp.com/connect-service-upstreams: 'example-https2:1234'
        #consul.hashicorp.com/connect-service-upstreams: 'static-server:1234'
        #consul.hashicorp.com/connect-service-upstreams: 'static-server-keine:1234'
        #consul.hashicorp.com/connect-service-upstreams: 'nginx:1234'
        #consul.hashicorp.com/connect-service-upstreams: 'dc1-nginx-no-ssl:1234'
        #consul.hashicorp.com/connect-service-upstreams: 'dc1-nginx-ssl:1234'
        consul.hashicorp.com/connect-service-upstreams: 'dc1-nginx-ssl:1234,dc1-nginx-no-ssl:1235'
        #consul.hashicorp.com/connect-service-upstreams: 'dc2-nginx-ssl:1234,dc2-nginx-no-ssl:1235'
        #consul.hashicorp.com/connect-service-upstreams: 'dc2-nginx-ssl:1234:dc2,dc2-nginx-no-ssl:1235:dc2'
      labels:
        app: static-client
    spec:
      serviceAccountName: static-client
      containers:
        - name: static-client
          #image: tutum/curl:latest
          image: curlimages/curl 
          ports:
            - containerPort: 4321
          #command: ['/bin/sh', '-c', '--']
          command: ["/bin/sleep", "3650d"]
          #args: ['while true; do sleep 30; done;']
