apiVersion: consul.hashicorp.com/v1alpha1
kind: TerminatingGateway
metadata:
  #name: terminating-gateway
  name: terminating-gateway-dc1
spec:
  services:
    - name: static-server-keine
      caFile: ca.pem

