apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: devops-by-example-v5
  region: us-east-1

nodeGroups:
  - name: nodes-general
    labels:
        role: workers
    instanceType: t2.small
    desiredCapacity: 2
    volumeSize: 20
