---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-backend
  name: simple-backend
  namespace: istioinaction
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: simple-backend
