apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-app-sm-enabled
---
apiVersion: v1
kind: Service
metadata:
  name: hello-app-sm-enabled-svc
spec:
  selector:
    app: hello-app-sm-enabled
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-app-sm-enabled
  name: hello-app-sm-enabled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app-sm-enabled
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/service-meta-version: "1"
        consul.hashicorp.com/service-tags: v1
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
        consul.hashicorp.com/connect-service-upstreams: 'world-app-sm-enabled:9999'
      labels:
        app: hello-app-sm-enabled
    spec:
      serviceAccountName: hello-app-sm-enabled
      containers:
      - env:
        - name: TEXT
          value: hello-app-sm-enabled
        - name: NEXT
          #value: world-app-sm-enabled.default.svc.cluster.local:8080
          value: localhost:9999
        image: vchaudh3/http-echo
        imagePullPolicy: Always
        name: hello-app-sm-enabled
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
