apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-producer-testclient
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kafka-producer-testclient
  name: kafka-producer-testclient
  annotations:
    consul.hashicorp.com/connect-inject: 'true'
    consul.hashicorp.com/service-meta-version: "1"
    consul.hashicorp.com/service-tags: v1
    prometheus.io/scrape: "true"
    prometheus.io/port: "9102"
    consul.hashicorp.com/connect-service-upstreams: 'kafka:9092'
spec:
  containers:
  - name: kafka-producer-testclient
    image: solsson/kafka:0.11.0.0
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-producer-testclient-svc
spec:
  selector:
    app: kafka-producer-testclient
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080

---
