apiVersion: v1
kind: Service
metadata:
  name: my-cluster-svc
spec:
  selector:
    #app: my-cluster
    name: my-cluster
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-cluster-kafka-bootstrap
spec:
  selector:
    #app: my-cluster
    name: my-cluster
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-cluster-kafka-brokers
spec:
  selector:
    #app: my-cluster
    name: my-cluster
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
