apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-producer
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    consul.hashicorp.com/connect-inject: 'true'
    consul.hashicorp.com/service-meta-version: "1"
    consul.hashicorp.com/service-tags: v1
    prometheus.io/scrape: "true"
    prometheus.io/port: "9102"
    #consul.hashicorp.com/connect-service-upstreams: 'world-app-sm-enabled:9999'
  labels:
    run: kafka-producer
  name: kafka-producer
spec:
  containers:
  - args:
    # - bin/kafka-console-producer.sh
    # - --broker-list
    # - my-cluster-kafka-bootstrap:9092
    # - --topic
    # - my-topic
    image: quay.io/strimzi/kafka:0.26.0-kafka-3.0.0
    imagePullPolicy: IfNotPresent
    name: kafka-producer

