apiVersion: v1
kind: Pod
metadata:
  name: testclient
  namespace: kafka
  annotations:
    consul.hashicorp.com/connect-inject: 'true'
    consul.hashicorp.com/service-meta-version: "1"
    consul.hashicorp.com/service-tags: v1
    prometheus.io/scrape: "true"
    prometheus.io/port: "9102"
    #consul.hashicorp.com/connect-service-upstreams: 'kafka-broker:9092'
spec:
  containers:
  - name: kafka
    image: solsson/kafka:0.11.0.0
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
