# permissions for end users to view cassandradatacenters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cassandradatacenter-viewer-role
rules:
- apiGroups:
  - cassandra.datastax.com
  resources:
  - cassandradatacenters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cassandra.datastax.com
  resources:
  - cassandradatacenters/status
  verbs:
  - get
